### ISSUE TITLE
Recent Posts

### ISSUE THREAD

**Issue by iamtakashi** [Automattic/blockpatterns#101]
This preview doesn't do justice :)

![Pattern 111](https://user-images.githubusercontent.com/908665/88209534-c1d79a00-cc4a-11ea-9121-b704553136d4.jpg)

```
<!-- wp:group {"align":"full","style":{"color":{"background":"#ffffff","text":"#000000"}}} -->
<div class="wp-block-group alignfull has-text-color has-background" style="background-color:#ffffff;color:#000000"><div class="wp-block-group__inner-container"><!-- wp:spacer {"height":64} -->
<div style="height:64px" aria-hidden="true" class="wp-block-spacer"></div>
<!-- /wp:spacer -->

<!-- wp:columns {"align":"wide"} -->
<div class="wp-block-columns alignwide"><!-- wp:column {"width":67} -->
<div class="wp-block-column" style="flex-basis:67%"><!-- wp:heading {"level":3,"style":{"typography":{"fontSize":34,"lineHeight":"1.25"}}} -->
<h3 style="font-size:34px;line-height:1.25">Latest from the Blog</h3>
<!-- /wp:heading --></div>
<!-- /wp:column -->

<!-- wp:column {"width":33} -->
<div class="wp-block-column" style="flex-basis:33%"></div>
<!-- /wp:column --></div>
<!-- /wp:columns -->

<!-- wp:a8c/blog-posts {"showAuthor":false,"postLayout":"grid","typeScale":3,"align":"wide"} /-->

<!-- wp:spacer {"height":64} -->
<div style="height:64px" aria-hidden="true" class="wp-block-spacer"></div>
<!-- /wp:spacer --></div></div>
<!-- /wp:group -->
```

**Comment by ianstewart** [comment]
LGTM with the same caveat as you. Do we have an issue yet for "Previews for Dynamic Blocks like Posts, Instagram, or Podcast Player"? The same caveat keeps coming up. cc @alaczek

**Comment by iamtakashi** [comment]
Related issues / chat: 
* https://github.com/Automattic/newspack-blocks/issues/430
* https://github.com/Automattic/jetpack/issues/15798
* CS0SC36SX/p1589429085121100-slack-dotcom-view-design

**Comment by ianstewart** [comment]
Thanks, I'm making a card to track that larger issue. (And maybe get some support on it.)

**Comment by pablohoneyhoney** [comment]
- Larger heading would create a better hierarchy. Or colored.
- Is the date formatted strangely with the dot?

**Comment by iamtakashi** [comment]
I've increased the heading one scale.

![Pattern 111](https://user-images.githubusercontent.com/908665/93772908-4dec4a80-fc17-11ea-9117-43def16384c7.jpg)

> Is the date formatted strangely with the dot?

Oh, the format will depend on the site setting "Date and time format". The last screenshot was taken with a custom format set in the master site, which I've changed to one of the defaults.
