### ISSUE TITLE
Support the Podcast CTA

### ISSUE THREAD

**Issue by alaczek** [Automattic/blockpatterns#136]
![image](https://user-images.githubusercontent.com/4550351/105646453-1c9cc780-5ef4-11eb-9841-cc1cf7583cd0.png)

```
<!-- wp:cover {"url":"https://dotcompatterns.files.wordpress.com/2021/01/t-shirts.jpg","id":3225,"dimRatio":0,"align":"full"} -->
<div class="wp-block-cover alignfull" style="background-image:url(https://dotcompatterns.files.wordpress.com/2021/01/t-shirts.jpg)"><div class="wp-block-cover__inner-container"><!-- wp:jetpack/layout-grid {"column1DesktopSpan":4,"column1TabletSpan":8,"column1MobileSpan":4,"column2DesktopOffset":8,"className":"column1-desktop-grid__span-4 column1-desktop-grid__row-1 column1-tablet-grid__span-8 column1-tablet-grid__row-1 column1-mobile-grid__span-4 column1-mobile-grid__row-1"} -->
<div class="wp-block-jetpack-layout-grid alignfull column1-desktop-grid__span-4 column1-desktop-grid__row-1 column1-tablet-grid__span-8 column1-tablet-grid__row-1 column1-mobile-grid__span-4 column1-mobile-grid__row-1"><!-- wp:jetpack/layout-grid-column -->
<div class="wp-block-jetpack-layout-grid-column wp-block-jetpack-layout-grid__padding-none"><!-- wp:heading {"style":{"typography":{"fontSize":"53px","lineHeight":"1.1"},"color":{"text":"#000000"}}} -->
<h2 class="has-text-color" style="color:#000000;font-size:53px;line-height:1.1">Organic<br>Cotton Tee</h2>
<!-- /wp:heading -->

<!-- wp:paragraph {"style":{"color":{"text":"#000000"}}} -->
<p class="has-text-color" style="color:#000000">Support the podcast by wearing the very latest in At the Fork apparel.</p>
<!-- /wp:paragraph -->

<!-- wp:buttons -->
<div class="wp-block-buttons"><!-- wp:button {"borderRadius":2,"style":{"color":{"background":"#000000"}}} -->
<div class="wp-block-button"><a class="wp-block-button__link has-background" style="border-radius:2px;background-color:#000000">Shop now</a></div>
<!-- /wp:button --></div>
<!-- /wp:buttons --></div>
<!-- /wp:jetpack/layout-grid-column --></div>
<!-- /wp:jetpack/layout-grid --></div></div>
<!-- /wp:cover -->
```

**Comment by ianstewart** [comment]
Twenty Twenty One editor styles.

![image](https://user-images.githubusercontent.com/545779/105899030-c3aa5d80-5fdf-11eb-9b71-34fefa140e7e.png)

And Twenty Twenty One front-end.

![image](https://user-images.githubusercontent.com/545779/105899082-d6bd2d80-5fdf-11eb-9a4b-9aba78bfe659.png)

Let's sort this one out and then 👍 .

**Comment by alaczek** [comment]
Pesky theme color palette strikes again 🤦‍♀️ I wonder if it would make sense for the editor to always save the hex value of the color even when picking from the theme palette? There's no consistency in the naming between the themes, and things can go particularly south if color has "foreground" or "background" in the name. I know in theory this should make for a seamless transition to a different theme (I think), but it's not working really well. 

I'd love to hear what others think!

Anyway, I updated the pattern to use hex values and it's looking good!

**Comment by ianstewart** [comment]
> There's no consistency in the naming between the themes, and things can go particularly south if color has "foreground" or "background" in the name. I know in theory this should make for a seamless transition to a different theme (I think), but it's not working really well.

It was my understanding that this was being looked in themes in general and we were moving away from pseudo-semantic colour names.

> Anyway, I updated the pattern to use hex values and it's looking good!

👍
