### ISSUE TITLE
Latest  Podcast Episode

### ISSUE THREAD

**Issue by alaczek** [Automattic/blockpatterns#139]
Here's a screenshot from Spearhead for this one:

![image](https://user-images.githubusercontent.com/4550351/105443528-073f5780-5cc0-11eb-8193-e12252c83895.png)

```
<!-- wp:spacer {"height":96} -->
<div style="height:96px" aria-hidden="true" class="wp-block-spacer"></div>
<!-- /wp:spacer -->

<!-- wp:jetpack/layout-grid {"column1DesktopSpan":6,"column1DesktopOffset":3,"column1TabletSpan":8,"column1MobileSpan":4,"column2DesktopOffset":4,"className":"column1-desktop-grid__span-6 column1-desktop-grid__start-4 column1-desktop-grid__row-1 column1-tablet-grid__span-8 column1-tablet-grid__row-1 column1-mobile-grid__span-4 column1-mobile-grid__row-1"} -->
<div class="wp-block-jetpack-layout-grid alignfull column1-desktop-grid__span-6 column1-desktop-grid__start-4 column1-desktop-grid__row-1 column1-tablet-grid__span-8 column1-tablet-grid__row-1 column1-mobile-grid__span-4 column1-mobile-grid__row-1"><!-- wp:jetpack/layout-grid-column -->
<div class="wp-block-jetpack-layout-grid-column wp-block-jetpack-layout-grid__padding-none"><!-- wp:a8c/blog-posts {"showDate":false,"moreButton":true,"showAuthor":false,"postsToShow":1,"sectionHeader":"Latest Episode"} /--></div>
<!-- /wp:jetpack/layout-grid-column --></div>
<!-- /wp:jetpack/layout-grid -->

<!-- wp:spacer {"height":96} -->
<div style="height:96px" aria-hidden="true" class="wp-block-spacer"></div>
<!-- /wp:spacer -->
```

**Comment by ianstewart** [comment]
Can we simplify this one to not use layout grid when used as a single pattern?

**Comment by alaczek** [comment]
We sure can! Here's how this would look like for comparison:

![image](https://user-images.githubusercontent.com/4550351/105936582-10f20200-60a8-11eb-8e10-0b1a768e5e42.png)

The narrower does look slightly better imo, but it makes sense not to overcomplicate in a pattern. Do we leave the top/bottom spacers in place tho?

**Comment by ianstewart** [comment]
I think the spacers help it a bit as a pattern in practice. Unless we throw it in a group with padding control?

**Comment by alaczek** [comment]
We could throw it into a group block. If we want to avoid spacers in general, then we'll need some kind of wrapper anyway, right?

This is the updated code:
```
<!-- wp:group {"align":"full","style":{"spacing":{"padding":{"top":"96px","bottom":"96px"}}}} -->
<div class="wp-block-group alignfull" style="padding-top:96px;padding-bottom:96px"><div class="wp-block-group__inner-container"><!-- wp:a8c/blog-posts {"showDate":false,"moreButton":true,"showAuthor":false,"postsToShow":1,"sectionHeader":"Latest Episode"} /--></div></div>
<!-- /wp:group -->
```

**Comment by alaczek** [comment]
This one is good to go... although I'm having second thoughts about the usefulness of this pattern :| I know we need a wide variety of patterns, but this one doesn't stand well on its own. I also think calling it a podcast episode might be confusing, as it implies podcast is somehow different than blog. What do you think @ianstewart?

**Comment by ianstewart** [comment]
I think with new query block patterns on the way from core (and us!) we might as well skip this one. Agreed.
