### ISSUE TITLE
Three Images Side by Side

### ISSUE THREAD

**Issue by iamtakashi** [Automattic/blockpatterns#17]
Simple three images side by side. No specific issue.

![three-images-side-by-side](https://user-images.githubusercontent.com/908665/76665526-16258b80-6580-11ea-9408-351aea39a0fd.png)

```
<!-- wp:jetpack/layout-grid {"addGutterEnds":false,"column1DesktopSpan":4,"column1TabletSpan":4,"column1MobileSpan":4,"column2DesktopSpan":4,"column2TabletSpan":4,"column2MobileSpan":4,"column3DesktopSpan":4,"column3TabletSpan":8,"column3MobileSpan":4,"className":"column1-desktop-grid__span-4 column1-desktop-grid__row-1 column2-desktop-grid__span-4 column2-desktop-grid__start-5 column2-desktop-grid__row-1 column3-desktop-grid__span-4 column3-desktop-grid__start-9 column3-desktop-grid__row-1 column1-tablet-grid__span-4 column1-tablet-grid__row-1 column2-tablet-grid__span-4 column2-tablet-grid__start-5 column2-tablet-grid__row-1 column3-tablet-grid__span-8 column3-tablet-grid__row-2 column1-mobile-grid__span-4 column1-mobile-grid__row-1 column2-mobile-grid__span-4 column2-mobile-grid__row-2 column3-mobile-grid__span-4 column3-mobile-grid__row-3"} -->
<div class="wp-block-jetpack-layout-grid alignfull column1-desktop-grid__span-4 column1-desktop-grid__row-1 column2-desktop-grid__span-4 column2-desktop-grid__start-5 column2-desktop-grid__row-1 column3-desktop-grid__span-4 column3-desktop-grid__start-9 column3-desktop-grid__row-1 column1-tablet-grid__span-4 column1-tablet-grid__row-1 column2-tablet-grid__span-4 column2-tablet-grid__start-5 column2-tablet-grid__row-1 column3-tablet-grid__span-8 column3-tablet-grid__row-2 column1-mobile-grid__span-4 column1-mobile-grid__row-1 column2-mobile-grid__span-4 column2-mobile-grid__row-2 column3-mobile-grid__span-4 column3-mobile-grid__row-3 wp-block-jetpack-layout-gutter__nowrap"><!-- wp:jetpack/layout-grid-column -->
<div class="wp-block-jetpack-layout-grid-column wp-block-jetpack-layout-grid__padding-none"><!-- wp:image {"id":9865,"sizeSlug":"full"} -->
<figure class="wp-block-image size-full"><img src="https://iamtakashi.files.wordpress.com/2020/03/taneli-lahtinen-odtdohyi6vw-unsplash-1.jpg" alt="" class="wp-image-9865"/></figure>
<!-- /wp:image --></div>
<!-- /wp:jetpack/layout-grid-column -->

<!-- wp:jetpack/layout-grid-column -->
<div class="wp-block-jetpack-layout-grid-column wp-block-jetpack-layout-grid__padding-none"><!-- wp:image {"id":9862,"sizeSlug":"full"} -->
<figure class="wp-block-image size-full"><img src="https://iamtakashi.files.wordpress.com/2020/03/taneli-lahtinen-utepqzzprmk-unsplash.jpg" alt="" class="wp-image-9862"/></figure>
<!-- /wp:image --></div>
<!-- /wp:jetpack/layout-grid-column -->

<!-- wp:jetpack/layout-grid-column -->
<div class="wp-block-jetpack-layout-grid-column wp-block-jetpack-layout-grid__padding-none"><!-- wp:image {"id":9861,"sizeSlug":"full"} -->
<figure class="wp-block-image size-full"><img src="https://iamtakashi.files.wordpress.com/2020/03/taneli-lahtinen-qfnbdwu6ijw-unsplash.jpg" alt="" class="wp-image-9861"/></figure>
<!-- /wp:image --></div>
<!-- /wp:jetpack/layout-grid-column --></div>
<!-- /wp:jetpack/layout-grid -->
```

**Comment by alaczek** [comment]
I wonder why do we need this particular block pattern? Wouldn't it make more sense to use image gallery in this case?

**Comment by iamtakashi** [comment]
> Wouldn't it make more sense to use image gallery in this case?

Using a gallery block has an advantage of the crop option that makes all the image the same size. I'm open to a suggestion but, in my opinion, using Layout Grid and Image blocks have several advantages.

* You can link each image to a page. I don't know if we can do that if you use a gallery.
* You can change the width of the image independently by changing the column width.
* It's easier to customize & extend — replace an image with text, add text below the image in each column etc.

**Comment by ianstewart** [comment]
I did [a quick comparison](https://patternshaper.wordpress.com/2020/03/16/three-images-side-by-side/) …

> You can link each image to a page. I don't know if we can do that if you use a gallery.

You can link to _anything_ with images in a layout grid. With the gallery you're limited to the attachment page or media file.

> You can change the width of the image independently by changing the column width.

True. Though a bit finicky. 

> It's easier to customize & extend — replace an image with text, add text below the image in each column etc.

This plus more exact control with the Layout Grid makes the layout grid approach makes it maybe more customizable.

That said, for the _Image Gallery_ …

Patterns that surfaced these settings …

![image](https://user-images.githubusercontent.com/545779/76776572-ec818580-6774-11ea-847e-7c81081dd625.png)

… will likely be popular.

**Comment by iamtakashi** [comment]
To add another benefit of using Layout Grid is that it has now the gutter setting that is missing in the Gallery block.

> Patterns that surfaced these settings … will likely be popular.

If I understand what you're saying, I totally agree. we should also be making patterns that purely use those gallery blocks because the visual thumbnails of patterns will most likely be more intuitive for many users than those icons.

**Comment by ianstewart** [comment]
> we should also be making patterns that purely use those gallery blocks because the visual thumbnails of patterns will most likely be more intuitive for many users than those icons.

Yep. That's what I'm meaning. :)
