### ISSUE TITLE
Image on left half

### ISSUE THREAD

**Issue by iamtakashi** [Automattic/blockpatterns#18]
A simple block with a 50/50 two column, an image on the left and the right is blank.

![image-left](https://user-images.githubusercontent.com/908665/76795749-e960b680-67c1-11ea-9de0-540314c51b90.jpg)

```
<!-- wp:jetpack/layout-grid {"addGutterEnds":false,"column1DesktopSpan":6,"column1TabletSpan":4,"column1MobileSpan":4,"column2DesktopSpan":6,"column2TabletSpan":4,"column2MobileSpan":4} -->
<div class="wp-block-jetpack-layout-grid alignfull column1-desktop-grid__span-6 column1-desktop-grid__row-1 column2-desktop-grid__span-6 column2-desktop-grid__start-7 column2-desktop-grid__row-1 column1-tablet-grid__span-4 column1-tablet-grid__row-1 column2-tablet-grid__span-4 column2-tablet-grid__start-5 column2-tablet-grid__row-1 column1-mobile-grid__span-4 column1-mobile-grid__row-1 column2-mobile-grid__span-4 column2-mobile-grid__row-2 wp-block-jetpack-layout-gutter__nowrap"><!-- wp:jetpack/layout-grid-column -->
<div class="wp-block-jetpack-layout-grid-column wp-block-jetpack-layout-grid__padding-none"><!-- wp:image {"id":53,"sizeSlug":"full"} -->
<figure class="wp-block-image size-full"><img src="https://iamtakashiblockpatterns.files.wordpress.com/2020/03/lionel-gustave-c1roy44wuts-unsplash.jpg" alt="" class="wp-image-53"/></figure>
<!-- /wp:image --></div>
<!-- /wp:jetpack/layout-grid-column -->

<!-- wp:jetpack/layout-grid-column -->
<div class="wp-block-jetpack-layout-grid-column wp-block-jetpack-layout-grid__padding-none"></div>
<!-- /wp:jetpack/layout-grid-column --></div>
<!-- /wp:jetpack/layout-grid -->
```

**Comment by ianstewart** [comment]
My first thought is, "Will this be confusing?"

**Comment by iamtakashi** [comment]
Confusing because the right column is blank?

**Comment by ianstewart** [comment]
Yeah, that was my first thought when looking at this pattern and the similar _Image on right half_. "Will users find this pattern confusing? Will they wonder if something is missing on the one side when they see it?"

**Comment by alaczek** [comment]
I can see this being useful for designers like us, building layouts, but agree that this might feel too abstract otherwise. How about we add a heading on the right, to make it more useful out of the box, but it would still be easy to remove that and have just the image. On the other hand that would be re-making Image + Text block... hmm.

**Comment by iamtakashi** [comment]
Thanks for the feedback. I'll work on this further 👍

**Comment by iamtakashi** [comment]
I've worked on a different pattern here: https://github.com/Automattic/blockpatterns/issues/29

I'm going to use this image for something else, but I'm closing this for now.
