### ISSUE TITLE
Payment Block 3 Columns

### ISSUE THREAD

**Issue by onuro** [Automattic/blockpatterns#189]
<img width="1437" alt="image" src="https://user-images.githubusercontent.com/645713/154328558-30d837f9-551e-4cf0-b7bb-efe68fba40c6.png">

[**Preview →**](https://dotcompatterns.wordpress.com/?p=4670&preview=true)

**Tricky bit:**
I've applied gradient background to the main columns block to be able to reproduce the full height dual color backgrounds in the columns.
<img width="1220" alt="Screen Shot 2022-02-17 at 01 52 37" src="https://user-images.githubusercontent.com/645713/154371264-cb7afd3e-4300-447c-a9a4-075577b45558.png">

```
<!-- wp:group {"align":"full"} -->
<div class="wp-block-group alignfull"><!-- wp:columns {"verticalAlignment":"bottom","align":"full","style":{"color":{"gradient":"linear-gradient(90deg,rgb(17,17,17) 48%,rgb(253,244,236) 48%)"},"spacing":{"padding":{"top":"0px","right":"0px","bottom":"0px","left":"0px"}}}} -->
<div class="wp-block-columns alignfull are-vertically-aligned-bottom has-background" style="background:linear-gradient(90deg,rgb(17,17,17) 48%,rgb(253,244,236) 48%);padding-top:0px;padding-right:0px;padding-bottom:0px;padding-left:0px"><!-- wp:column {"verticalAlignment":"bottom"} -->
<div class="wp-block-column is-vertically-aligned-bottom"><!-- wp:group {"style":{"spacing":{"padding":{"top":"60px","right":"40px","bottom":"70px","left":"40px"},"blockGap":"35px"},"color":{"background":"#111111"}},"layout":{"contentSize":"90%"}} -->
<div class="wp-block-group has-background" style="background-color:#111111;padding-top:60px;padding-right:40px;padding-bottom:70px;padding-left:40px"><!-- wp:heading {"textAlign":"left","style":{"typography":{"fontSize":"44px","fontStyle":"normal","fontWeight":"600"},"color":{"text":"#fefefe"}}} -->
<h2 class="has-text-align-left has-text-color" id="a-pendant-that-fits-your-style" style="color:#fefefe;font-size:44px;font-style:normal;font-weight:600">A pendant that fits your style</h2>
<!-- /wp:heading -->

<!-- wp:group {"style":{"spacing":{"margin":{"bottom":"40px"}}}} -->
<div class="wp-block-group" style="margin-bottom:40px"><!-- wp:paragraph {"align":"left","style":{"color":{"text":"#999999"},"typography":{"fontSize":"17px"}}} -->
<p class="has-text-align-left has-text-color" style="color:#999999;font-size:17px">Meeting the highest standards, this silver necklace is made out of pure silver and gold chain. Best for pairing with summer clothing.</p>
<!-- /wp:paragraph --></div>
<!-- /wp:group -->

<!-- wp:jetpack/recurring-payments -->
<div class="wp-block-jetpack-recurring-payments"><!-- wp:jetpack/button {"element":"a","uniqueId":"recurring-payments-id","text":"\u003cstrong\u003eBuy Now\u003c/strong\u003e →","customTextColor":"#111111","customBackgroundColor":"#fffffe","borderRadius":0,"width":"200px"} /--></div>
<!-- /wp:jetpack/recurring-payments --></div>
<!-- /wp:group --></div>
<!-- /wp:column -->

<!-- wp:column {"verticalAlignment":"bottom","style":{"spacing":{"padding":{"top":"0px","right":"0px","bottom":"0px","left":"0px"}}}} -->
<div class="wp-block-column is-vertically-aligned-bottom" style="padding-top:0px;padding-right:0px;padding-bottom:0px;padding-left:0px"><!-- wp:group -->
<div class="wp-block-group"><!-- wp:image {"align":"center","id":4416,"sizeSlug":"full","linkDestination":"none"} -->
<figure class="wp-block-image aligncenter size-full"><img src="https://dotcompatterns.files.wordpress.com/2022/02/pendant.jpg" alt="" class="wp-image-4416"/></figure>
<!-- /wp:image --></div>
<!-- /wp:group --></div>
<!-- /wp:column -->

<!-- wp:column {"verticalAlignment":"bottom","style":{"spacing":{"padding":{"top":"40px","right":"2%","bottom":"60px","left":"2%"}},"color":{"background":"#fdf4ec"}}} -->
<div class="wp-block-column is-vertically-aligned-bottom has-background" style="background-color:#fdf4ec;padding-top:40px;padding-right:2%;padding-bottom:60px;padding-left:2%"><!-- wp:group {"style":{"spacing":{"blockGap":"30px"}}} -->
<div class="wp-block-group"><!-- wp:group {"style":{"color":{"text":"#555555"},"spacing":{"padding":{"bottom":"0px","top":"0px","right":"0px","left":"0px"},"blockGap":"30px"}},"layout":{"contentSize":"90%"}} -->
<div class="wp-block-group has-text-color" style="color:#555555;padding-top:0px;padding-right:0px;padding-bottom:0px;padding-left:0px"><!-- wp:heading {"level":4,"style":{"typography":{"fontStyle":"normal","fontWeight":"600","fontSize":"22px"},"color":{"text":"#111111"}}} -->
<h4 class="has-text-color" id="pure-silver-with-gold-chain-1" style="color:#111111;font-size:22px;font-style:normal;font-weight:600">Pure Silver with Gold Chain</h4>
<!-- /wp:heading -->

<!-- wp:paragraph {"style":{"typography":{"fontSize":"17px"}}} -->
<p style="font-size:17px">The design is made in Pure 92.5 % silver, coupled with the 24 carat gold chain.</p>
<!-- /wp:paragraph -->

<!-- wp:separator {"customColor":"#e7e7e7","className":"is-style-wide"} -->
<hr class="wp-block-separator has-text-color has-background is-style-wide" style="background-color:#e7e7e7;color:#e7e7e7"/>
<!-- /wp:separator --></div>
<!-- /wp:group -->

<!-- wp:group {"style":{"color":{"text":"#555555"},"spacing":{"padding":{"bottom":"0px","top":"0px","right":"0px","left":"0px"},"blockGap":"30px"}},"layout":{"contentSize":"90%"}} -->
<div class="wp-block-group has-text-color" style="color:#555555;padding-top:0px;padding-right:0px;padding-bottom:0px;padding-left:0px"><!-- wp:heading {"level":4,"style":{"typography":{"fontStyle":"normal","fontWeight":"600","fontSize":"22px"},"color":{"text":"#111111"}}} -->
<h4 class="has-text-color" id="pure-silver-with-gold-chain-1" style="color:#111111;font-size:22px;font-style:normal;font-weight:600">Lightweight</h4>
<!-- /wp:heading -->

<!-- wp:paragraph {"style":{"typography":{"fontSize":"17px"}}} -->
<p style="font-size:17px">The pendant is lightweight and versatile. Great to wear with a summer dress.</p>
<!-- /wp:paragraph -->

<!-- wp:separator {"customColor":"#e7e7e7","className":"is-style-wide"} -->
<hr class="wp-block-separator has-text-color has-background is-style-wide" style="background-color:#e7e7e7;color:#e7e7e7"/>
<!-- /wp:separator --></div>
<!-- /wp:group -->

<!-- wp:group {"style":{"color":{"text":"#555555"},"spacing":{"padding":{"bottom":"0px","top":"0px","right":"0px","left":"0px"},"blockGap":"30px"}},"layout":{"contentSize":"90%"}} -->
<div class="wp-block-group has-text-color" style="color:#555555;padding-top:0px;padding-right:0px;padding-bottom:0px;padding-left:0px"><!-- wp:heading {"level":4,"style":{"typography":{"fontStyle":"normal","fontWeight":"600","fontSize":"22px"},"color":{"text":"#111111"}}} -->
<h4 class="has-text-color" id="pure-silver-with-gold-chain-1" style="color:#111111;font-size:22px;font-style:normal;font-weight:600">30-Day Warranty</h4>
<!-- /wp:heading -->

<!-- wp:paragraph {"style":{"typography":{"fontSize":"17px"}}} -->
<p style="font-size:17px">Every piece of jewellery sold at our store is covered under our 30-Day Replacement Guarantee.</p>
<!-- /wp:paragraph --></div>
<!-- /wp:group --></div>
<!-- /wp:group --></div>
<!-- /wp:column --></div>
<!-- /wp:columns --></div>
<!-- /wp:group -->

```

@ianstewart @olaolusoga @alaczek @iamtakashi

**Comment by alaczek** [comment]
I really like this design, nice job Onur!

One thing I noticed is how my eye keeps being drawn to the right column, but the buy button is on the left column - maybe you could do an experiment with swapping places of these two columns? 

The background color not stretching full column width is something I encountered and reported a while back: https://github.com/WordPress/gutenberg/issues/32907

It's a bummer it still isn't solved because it would make the setup much easier. Maybe keep tabs on it and when the fix lands we can swap?

**Comment by alaczek** [comment]
Oh, don't forget to swap out the buttons block for payments :D

**Comment by onuro** [comment]
Update: patterns itself and code snippet updated with font sizing matches w the design

**Comment by iamtakashi** [comment]
Thanks for updating the pattern.

- I think it needs a stronger connection between the column with a white background and the rest. Have you tried to add a background colour that ties it better to the rest?
- Right-aligned text sometimes makes a design interesting, but I'm not sure if this pattern is appropriate for it. I struggle to read the paragraph that needs to convince me to click the Buy button.
- It might be worth playing with the vertical alignment for the text. The text in both columns floating in the middle makes the design less striking.
- You can specify line height for all the text as well.

**Comment by iamtakashi** [comment]
I forgot to mention this. Is the use of 90% width applied to the group block necessary? It might be making the pattern unnecessarily complicated. If you definitely need wider gutters, it might be possible by increasing the padding in the column block.

**Comment by onuro** [comment]
Thanks @iamtakashi! 

> * I think it needs a stronger connection between the column with a white background and the rest. Have you tried to add a background colour that ties it better to the rest?

Do you mean a subtle background instead of white on the third column or the alternate bg color for the dark column one?

> * Right-aligned text sometimes makes a design interesting, but I'm not sure if this pattern is appropriate for it. I struggle to read the paragraph that needs to convince me to click the Buy button.
In the design it didn't feel wrong but with actual pattern, I think you have a point. Left aligning all seems better.

> * It might be worth playing with the vertical alignment for the text. The text in both columns floating in the middle makes the design less striking.
Interesting and thanks, good call.

Re the 90% width column, the larger and closer to the design fixed px padding really took away a lot in mobile, so I wanted to try percentage widths. But you're right, it might feel a bit awkward for a novice user trying the pattern.

I'll revisit this and update shortly.

**Comment by iamtakashi** [comment]
> Do you mean a subtle background instead of white on the third column or the alternate bg color for the dark column one?

I was thinking to add a subtle background instead of white, but I haven't tested :) 

> fixed px padding really took away a lot in mobile, so I wanted to try percentage widths.

Yeah, fixed pixel pudding wouldn't work for small screens. You already have side padding in % for the 3rd column so I was wondering if you could increase the padding instead of narrowing down the Group block to 90%.

**Comment by alaczek** [comment]
> I was thinking to add a subtle background instead of white

Yeah, maybe light beige?

**Comment by iamtakashi** [comment]
Thanks for the update! 

With the left-aligned text, it looks better. It might be the screenshot, I'm not sure about the background colour. It might be better if it has a tiny bit more yellow so it reminds a bit of the colour of the t-shirt/top. Something like `#faefe5`?

Re: Vertical alignment
What do you think if both texts are aligned at the bottom? It would probably look better if the left column has less text like before.

**Comment by onuro** [comment]
Thanks Takashi.

I've updated but #faefe5 felt like there it was a little too much, so I'm attaching a tone in between.

<img width="1437" alt="image" src="https://user-images.githubusercontent.com/645713/157174803-74e029b8-1a98-438a-8f7f-4cd20ada339e.png">


With #faefe5
<img width="1438" alt="Screen Shot 2022-03-08 at 08 10 57" src="https://user-images.githubusercontent.com/645713/157174858-b30dbd28-6205-4a92-8561-4a1f4b71d3d4.png">

The difference may be very minor, but let me know :)

**Comment by iamtakashi** [comment]
Nice, the lighter one works 👍 A white button is certainly worth a try.

**Comment by onuro** [comment]
Updated w white button. Feels more like it :)

<img width="1491" alt="image" src="https://user-images.githubusercontent.com/645713/158120566-172b93a0-73ce-44b6-80d2-ae465634927a.png">

**Comment by iamtakashi** [comment]
Yeah, the white button works. Do you want to keep the text in the left column right-aligned?

**Comment by onuro** [comment]
@iamtakashi yeah I did try but somehow when the price is on the right of the button, the price gets a top margin on it's paragraph in the theme, making it look awkward.

<img width="1625" alt="image" src="https://user-images.githubusercontent.com/645713/159215469-47d9b79d-23d3-42e7-85a2-42447cfeb4a4.png">

No issues when price aligned before the button(probably theme's paragraph first-child margin top zeroing out).

I'll probably remove the price tag if we'll go with left aligned first column text

**Comment by onuro** [comment]
Updated without price tag

<img width="1679" alt="image" src="https://user-images.githubusercontent.com/645713/159216807-55fb5624-0ddb-4cb8-8ae7-c74a838ad05e.png">

**Comment by iamtakashi** [comment]
Thanks for the update. It's looking good! 👍 

> PS: I've added block spacing in the group block to the first column blocks but somehow theme is ignoring it:

Yeah, I've also noticed there are bugs with a paragraph block in Blockbase.

- https://github.com/Automattic/themes/issues/5616
- https://github.com/Automattic/themes/issues/5617
