### ISSUE TITLE
Payment Block Description

### ISSUE THREAD

**Issue by onuro** [Automattic/blockpatterns#197]
<img width="960" alt="image" src="https://user-images.githubusercontent.com/645713/160002075-3bc1efa3-ffda-4726-9b8d-4e8718bd9dc2.png">

[Preview →](https://dotcompatterns.wordpress.com/?p=4686&preview=true)

@ianstewart @olaolusoga @alaczek @iamtakashi

```

<!-- wp:group {"align":"full","style":{"spacing":{"padding":{"top":"40px","right":"40px","bottom":"40px","left":"40px"}},"color":{"background":"#eaf3f3","text":"#434343"}},"layout":{"contentSize":"1000px"}} -->
<div class="wp-block-group alignfull has-text-color has-background" style="background-color:#eaf3f3;color:#434343;padding-top:40px;padding-right:40px;padding-bottom:40px;padding-left:40px"><!-- wp:columns {"align":"wide"} -->
<div class="wp-block-columns alignwide"><!-- wp:column -->
<div class="wp-block-column"><!-- wp:gallery {"columns":1,"linkTo":"none"} -->
<figure class="wp-block-gallery has-nested-images columns-1 is-cropped"><!-- wp:image {"id":4849,"sizeSlug":"full","linkDestination":"none"} -->
<figure class="wp-block-image size-full"><img src="https://dotcompatterns.files.wordpress.com/2022/03/jack1.jpg" alt="" class="wp-image-4849"/></figure>
<!-- /wp:image -->

<!-- wp:image {"id":4848,"sizeSlug":"full","linkDestination":"none"} -->
<figure class="wp-block-image size-full"><img src="https://dotcompatterns.files.wordpress.com/2022/03/jack2.jpg" alt="" class="wp-image-4848"/></figure>
<!-- /wp:image --></figure>
<!-- /wp:gallery --></div>
<!-- /wp:column -->

<!-- wp:column {"width":"450px","style":{"spacing":{"padding":{"top":"0px","right":"30px","bottom":"30px","left":"30px"}}}} -->
<div class="wp-block-column" style="padding-top:0px;padding-right:30px;padding-bottom:30px;padding-left:30px;flex-basis:450px"><!-- wp:heading {"style":{"color":{"text":"#0a0a0a"},"typography":{"fontSize":"48px","fontStyle":"normal","fontWeight":"700","lineHeight":1.1},"spacing":{"margin":{"bottom":"0px","top":"0px"}}}} -->
<h2 class="has-text-color" id="the-renew-long-parka" style="color:#0a0a0a;font-size:48px;font-style:normal;font-weight:700;line-height:1.1;margin-top:0px;margin-bottom:0px">Stewart Blue Jean Jacket</h2>
<!-- /wp:heading -->

<!-- wp:paragraph {"style":{"typography":{"fontSize":"28px"}}} -->
<p style="font-size:28px">$366</p>
<!-- /wp:paragraph -->

<!-- wp:paragraph -->
<p>Wear your true size to get an effortless fits like a glove look or size up and you’ve got the perfect layer to toss over your favorite hoodie.</p>
<!-- /wp:paragraph -->

<!-- wp:group {"style":{"spacing":{"blockGap":"10px","padding":{"right":"0px","bottom":"0px"},"margin":{"top":"0px","bottom":"40px"}},"visualizers":{"margin":{"bottom":true}}}} -->
<div class="wp-block-group" style="margin-top:0px;margin-bottom:40px;padding-right:0px;padding-bottom:0px"><!-- wp:paragraph {"style":{"typography":{"fontStyle":"normal","fontWeight":"700"}}} -->
<p style="font-style:normal;font-weight:700">Description</p>
<!-- /wp:paragraph -->

<!-- wp:paragraph -->
<p>Stewart Jacket makes an outfit—and its style endures beyond seasons and trends. </p>
<!-- /wp:paragraph -->

<!-- wp:paragraph -->
<p>Meant to be worn forever, wherever, whenever, you’d be hard-pressed to find a jacket with an easier shape, more versatile weight or inherent sense of cool.</p>
<!-- /wp:paragraph --></div>
<!-- /wp:group -->

<!-- wp:group {"style":{"spacing":{"blockGap":"40px"}}} -->
<div class="wp-block-group"><!-- wp:jetpack/recurring-payments -->
<div class="wp-block-jetpack-recurring-payments"><!-- wp:jetpack/button {"element":"a","uniqueId":"recurring-payments-id","text":"\u003cstrong\u003eBuy Now\u003c/strong\u003e","customTextColor":"#fefefe","customBackgroundColor":"#071a1e","borderRadius":0,"width":"100%"} /--></div>
<!-- /wp:jetpack/recurring-payments --></div>
<!-- /wp:group --></div>
<!-- /wp:column --></div>
<!-- /wp:columns --></div>
<!-- /wp:group -->

```

**Comment by alaczek** [comment]
Sadly, we can't use those images and text - they were pulled from an actual online store (which I found when I was launching Winkel)

More importantly, this feels more like a layout comprised of two patterns (the product + the testimonial). So maybe we launch this as a layout, and the product part separately as a pattern? The quote part, I'm not sure I'd launch on it's own - we do have quite a few quote blocks.

**Comment by iamtakashi** [comment]
Plus 1 on removing the quote part from the pattern.

I can see a bit of mismatching details between the mockup and the preview of the pattern.

* Can you remove the extra spacing (1), (3), (4)
* Reduce the line-height for the title (2)
* The paragraph seems to be a bit larger?
* I think it'd be nice to remove the round corners from the button.

**Comment by onuro** [comment]
Hey folks, how about this set of images?

<img width="1363" alt="image" src="https://user-images.githubusercontent.com/645713/157229903-1b657868-a61a-43c7-8310-741c806db2be.png">

**Comment by iamtakashi** [comment]
Just realised I forgot to add this to my feedback. Sorry about that!

<img width="1277" alt="Screenshot 2022-03-02 at 16 05 55" src="https://user-images.githubusercontent.com/908665/157512780-56a9ede5-6406-48fb-ac8f-555621275ab8.png">

The images are "ok" but then I think we should change the background colour as well.

**Comment by onuro** [comment]
Ah perfect thanks! updating shortly

**Comment by onuro** [comment]
Updated w margin fixes:

<img width="1494" alt="image" src="https://user-images.githubusercontent.com/645713/158122095-e721239d-e26f-4baa-bdbf-49c308a1b9f9.png">

**Comment by iamtakashi** [comment]
Thanks for the update. For some reason, there is no gap between the button and the paragraph for me. https://dotcompatterns.wordpress.com/?p=4686&preview=true

What do you think about changing the background colour to one with a tiny hint of blue so it ties to the jacket?

<img width="458" alt="Screenshot 2022-03-14 at 13 06 56" src="https://user-images.githubusercontent.com/908665/158178779-fef29f72-e58c-41c1-a160-fd1c569e100e.png">

**Comment by onuro** [comment]
Updated. Yeah theme eliminates some of the margins in the front end somehow. Added bottom margin to the group block above the button to fix it:

<img width="1258" alt="image" src="https://user-images.githubusercontent.com/645713/159219231-9efddca2-5223-4f3e-aaac-d8c51fb2c228.png">

**Comment by iamtakashi** [comment]
Thanks for the update. It looks good 👍
