### ISSUE TITLE
Payment Block Cover Dark

### ISSUE THREAD

**Issue by onuro** [Automattic/blockpatterns#198]
<img width="1425" alt="image" src="https://user-images.githubusercontent.com/645713/159989348-d96ca1b8-1741-4a06-b68e-9a9b9b93c6c0.png">

[Preview →](https://dotcompatterns.wordpress.com/?p=4688&preview=true)

@ianstewart @olaolusoga @alaczek @iamtakashi

```

<!-- wp:cover {"customOverlayColor":"#161005","align":"full","style":{"spacing":{"padding":{"top":"5%","right":"5%","bottom":"5%","left":"5%"}}}} -->
<div class="wp-block-cover alignfull" style="padding-top:5%;padding-right:5%;padding-bottom:5%;padding-left:5%"><span aria-hidden="true" class="wp-block-cover__background has-background-dim-100 has-background-dim" style="background-color:#161005"></span><div class="wp-block-cover__inner-container"><!-- wp:media-text {"align":"full","mediaPosition":"right","mediaId":4907,"mediaType":"image","mediaWidth":55,"mediaSizeSlug":"full","verticalAlignment":"bottom","imageFill":false} -->
<div class="wp-block-media-text alignfull has-media-on-the-right is-stacked-on-mobile is-vertically-aligned-bottom" style="grid-template-columns:auto 55%"><figure class="wp-block-media-text__media"><img src="https://dotcompatterns.files.wordpress.com/2022/03/frame-1.jpg?w=872" alt="" class="wp-image-4907 size-full"/></figure><div class="wp-block-media-text__content"><!-- wp:group {"style":{"spacing":{"padding":{"top":"30px","right":"30px","bottom":"0px","left":"0px"},"blockGap":"0px"},"color":{"text":"#fffffe"}},"layout":{"contentSize":"423px"}} -->
<div class="wp-block-group has-text-color" style="color:#fffffe;padding-top:30px;padding-right:30px;padding-bottom:0px;padding-left:0px"><!-- wp:heading {"style":{"typography":{"fontSize":"59px","fontStyle":"normal","fontWeight":"700"},"spacing":{"margin":{"bottom":"40px"}}}} -->
<h2 id="my-book" style="font-size:59px;font-style:normal;font-weight:700;margin-bottom:40px">My Book</h2>
<!-- /wp:heading -->

<!-- wp:paragraph {"style":{"typography":{"fontSize":"17px","lineHeight":"1.6"},"color":{"text":"#cacaca"}}} -->
<p class="has-text-color" style="color:#cacaca;font-size:17px;line-height:1.6">A New York Times Bestseller. This book will take you to a mystic journey. It's the story of Sanjeet, a young boy with big dreams for his life. Grab this copy before the stocks last! </p>
<!-- /wp:paragraph -->

<!-- wp:spacer {"height":"40px"} -->
<div style="height:40px" aria-hidden="true" class="wp-block-spacer"></div>
<!-- /wp:spacer -->

<!-- wp:jetpack/recurring-payments {"shouldDisplayFrontendBanner":false} -->
<div class="wp-block-jetpack-recurring-payments"><!-- wp:jetpack/button {"element":"a","uniqueId":"recurring-payments-id","text":"\u003cstrong\u003eBuy the book now\u003c/strong\u003e","customTextColor":"#fefefe","customBackgroundColor":"#aa7234","borderRadius":0,"width":"100%"} /--></div>
<!-- /wp:jetpack/recurring-payments --></div>
<!-- /wp:group --></div></div>
<!-- /wp:media-text --></div></div>
<!-- /wp:cover -->

```

**Comment by alaczek** [comment]
When I tried this pattern, the proportion of image to text felt off. I think the text column should be narrower - maybe 400px? And the padding on the right of the text column could be beefed up.

**Comment by iamtakashi** [comment]
Have you considered getting rid of the side padding(1) so that the pattern would have the same side padding? That would help the pattern on small screens too.

What do you think about removing the bottom padding (2) below the button?

I get the intent, but the title "My Book" isn't especially inspiring. It's probably better if it was actually the title of the book?

<img width="1278" alt="Screenshot 2022-03-02 at 15 43 41" src="https://user-images.githubusercontent.com/908665/156398162-5664d420-ffa1-4319-a04f-bef25645f58a.png">

**Comment by onuro** [comment]
Changes applied are as follows:

- Paddings reworked
- Title updated
- Pattern preview post link fix

**Comment by iamtakashi** [comment]
Thanks for updating! 

This is my fault. The book in the image is an actual product that someone is selling elsewhere, and we shouldn't use it for a pattern like this (Just like the one with Boxwater).

What I've done previously for a case like this was to use a product mockup like [these](https://www.free-mockup.com/downloads/category/product-design/) and make a bogus product instead of using images from Unsplash or Pexels.

**Comment by onuro** [comment]
Updated w custom mockup:

<img width="1561" alt="image" src="https://user-images.githubusercontent.com/645713/159217342-43ef7eb9-bc12-427a-b0d4-404f0166ead4.png">

**Comment by iamtakashi** [comment]
The image looks good. It's hard to tell it's been photoshopped :) We want to update the title, don't we? Since the title is longer, we probably need it to be smaller.

**Comment by onuro** [comment]
Great. The title was way too long, so I just called it "My Book"

<img width="797" alt="image" src="https://user-images.githubusercontent.com/645713/159978251-5cfd781a-5ce9-4841-af1a-1cb3a556ee32.png">

What do you think?

**Comment by iamtakashi** [comment]
Yeah :) I think that's fine. I think this is good to go 👍
