### ISSUE TITLE
Call to Action with Cover Block

### ISSUE THREAD

**Issue by iamtakashi** [Automattic/blockpatterns#201]
![dotcompatterns wordpress com__p=5274 preview=true](https://user-images.githubusercontent.com/908665/165576608-356ca28d-787a-4920-8ff0-b7c76ecfbe1f.png)

[Preview](https://dotcompatterns.wordpress.com/?p=5274&preview=true)

```
<!-- wp:group {"align":"full","style":{"spacing":{"blockGap":{"top":"0px","left":"0px"}}},"layout":{"inherit":true}} -->
<div class="wp-block-group alignfull"><!-- wp:cover {"url":"https://dotcompatterns.files.wordpress.com/2022/04/stijn-te-strake-vbsqbhmxsxw-unsplash.jpg","id":5278,"dimRatio":0,"focalPoint":{"x":"0.76","y":"0.23"},"minHeight":75,"minHeightUnit":"vh","contentPosition":"center left","isDark":false,"align":"full","style":{"spacing":{"padding":{"top":"7vw","right":"7vw","bottom":"7vw","left":"7vw"}}}} -->
<div class="wp-block-cover alignfull is-light has-custom-content-position is-position-center-left" style="padding-top:7vw;padding-right:7vw;padding-bottom:7vw;padding-left:7vw;min-height:75vh"><span aria-hidden="true" class="wp-block-cover__background has-background-dim-0 has-background-dim"></span><img class="wp-block-cover__image-background wp-image-5278" alt="" src="https://dotcompatterns.files.wordpress.com/2022/04/stijn-te-strake-vbsqbhmxsxw-unsplash.jpg" style="object-position:76% 23%" data-object-fit="cover" data-object-position="76% 23%"/><div class="wp-block-cover__inner-container"><!-- wp:group {"style":{"elements":{"link":{"color":{"text":"var:preset|color|white"}}}},"textColor":"white","layout":{"contentSize":"520px"}} -->
<div class="wp-block-group has-white-color has-text-color has-link-color"><!-- wp:heading {"level":1,"style":{"typography":{"fontSize":"3.375rem","lineHeight":1.1}}} -->
<h1 style="font-size:3.375rem;line-height:1.1"><strong>Collect moments, not things.</strong></h1>
<!-- /wp:heading -->

<!-- wp:paragraph {"style":{"typography":{"fontSize":"1.125rem","lineHeight":1.6}}} -->
<p style="font-size:1.125rem;line-height:1.6"><a href="#"><strong><span style="text-decoration:underline;">Explore our tours</span></strong></a></p>
<!-- /wp:paragraph --></div>
<!-- /wp:group --></div></div>
<!-- /wp:cover --></div>
<!-- /wp:group -->
```

cc @alaczek @onuro

**Comment by onuro** [comment]
Nice one @iamtakashi . I've just tested out a bigger font for the heading, which I think matches better with the scale of the cover size. What do you think?

<img width="1725" alt="image" src="https://user-images.githubusercontent.com/645713/165541853-be2255af-a6bd-4d71-9b53-df22fa6aa9af.png">

**Comment by iamtakashi** [comment]
Sure, I've updated the heading a bit larger (equivalent to 54px).

**Comment by alaczek** [comment]
I'm wondering about making the column wider. 35% width means the heading wraps into three lines when a browser window is under 1450px. What do you think?

<img width="1353" alt="image" src="https://user-images.githubusercontent.com/4550351/165666308-16dc636d-8b46-4d77-a453-9b9451553f41.png">

**Comment by iamtakashi** [comment]
Scratch that; it wasn't good enough.

With [the help of Justin Tadlock](https://wptavern.com/how-to-align-a-nested-partial-width-group-block-via-the-wordpress-editor), it works much better for all the viewports. See it in the preview!

I'll update our patterns that can benefit from the technique.
