### ISSUE TITLE
Centered header

### ISSUE THREAD

**Issue by alaczek** [Automattic/blockpatterns#210]
<img width="1421" alt="image" src="https://user-images.githubusercontent.com/4550351/179644765-6dc294bc-6abc-4ff1-a43a-a5395c0bde17.png">

```
<!-- wp:group {"align":"full","style":{"spacing":{"padding":{"top":"2em","bottom":"4em"}}}} -->
<div class="wp-block-group alignfull" style="padding-top:2em;padding-bottom:4em"><!-- wp:site-logo {"align":"center"} /-->

<!-- wp:site-title {"textAlign":"center","fontSize":"large"} /-->

<!-- wp:navigation {"layout":{"type":"flex","justifyContent":"center"}} /--></div>
<!-- /wp:group -->
```
https://dotcompatterns.wordpress.com/?p=5579&preview=true

**Comment by iamtakashi** [comment]
I think It'd be helpful for users to see the placeholder-looking logo for a header pattern like this. Can we add this image as the logo in the pattern? 

https://headerandfooterpatterns.files.wordpress.com/2022/01/ba5d5-site-logo.png

**Comment by iamtakashi** [comment]
> Can we add this image as the logo in the pattern?

Hmm... I'm actually not sure if adding a site logo to dotcompatterns through this pattern will actually help anything. Will it be blank for the site that doesn't have a logo anyway? I guess it's worth testing with this? :)

**Comment by onuro** [comment]
+1 on this. I think we need to tinker on ways to demo content in patterns even if they're WP db based(content showing up only if you have logo/post/nav on your site etc).

**Comment by alaczek** [comment]
> Can we add this image as the logo in the pattern?
It's not possible as far as I know. Even if you upload a logo on a test site and look at the resulting code, the path to the image source isn't there, so there's no way to pass on a default. I think we should still proceed with patterns that include logos nonetheless. 

> I think we need to tinker on ways to demo content in patterns even if they're WP db based
@onuro could you elaborate on what you mean by that?

**Comment by alaczek** [comment]
I updated the code because I realized the nav menu wasn't centred.

**Comment by alaczek** [comment]
Published!
