### ISSUE TITLE
Centered Header with Logo and Navigation

### ISSUE THREAD

**Issue by alaczek** [Automattic/blockpatterns#220]
<img width="927" alt="image" src="https://user-images.githubusercontent.com/4550351/179652118-ffdcf6d0-b6b3-4408-9822-918d9c13bfe4.png">

```
<!-- wp:group {"align":"full"} -->
<div class="wp-block-group alignfull"><!-- wp:group {"style":{"spacing":{"blockGap":"80px"}},"layout":{"type":"flex","flexWrap":"nowrap","justifyContent":"center"}} -->
<div class="wp-block-group"><!-- wp:navigation {"layout":{"type":"flex","justifyContent":"right"}} -->
<!-- wp:navigation-link {"label":"Home","url":"#","isTopLevelLink":true} /-->

<!-- wp:navigation-link {"label":"About","url":"#","isTopLevelLink":true} /-->
<!-- /wp:navigation -->

<!-- wp:site-logo /-->

<!-- wp:navigation -->
<!-- wp:navigation-link {"label":"Blog","url":"#","isTopLevelLink":true} /-->

<!-- wp:navigation-link {"label":"Contact","url":"#","isTopLevelLink":true} /-->
<!-- /wp:navigation --></div>
<!-- /wp:group --></div>
<!-- /wp:group -->
```
https://dotcompatterns.wordpress.com/?p=5608&preview=true

**Comment by onuro** [comment]
Nice one!

**Comment by iamtakashi** [comment]
Can we do the same for the logo and navigation? The preview in dotcompatterns is looking sad.

![Screenshot 2022-07-19 at 19 06 00](https://user-images.githubusercontent.com/908665/179819063-7bc8c865-ee95-48ab-aacf-12a3c7ee686b.jpg)

I _think_ this is how it appears on the inserter for a site that doesn't have a navigation or a site logo, right?

**Comment by onuro** [comment]
I think it's due the fact that it pulls your existing navigation @iamtakashi and if none, doesn't display anything.

**Comment by alaczek** [comment]
The image preview above is from Figma, in the editor you get navigation block placeholders:

<img width="1285" alt="image" src="https://user-images.githubusercontent.com/4550351/179867705-66b4a722-e31c-4b37-a89a-84a17a0f41b0.png">

And as you noted, the preview on the front end is just blank, until you set up the logo and menus.
I do think adding "dummy" menu items makes a lot of sense, otherwise, the preview is quite underwhelming.

**Comment by alaczek** [comment]
I added the default nav links to both menus so that the preview shows something:

<img width="1412" alt="image" src="https://user-images.githubusercontent.com/4550351/180924796-59530164-fc3a-4d04-bef8-195b9f4095b2.png">

I'm on the fence about publishing this one because the lack of a logo in the preview makes it look a bit off, but the pattern overall feels very useful.

**Comment by alaczek** [comment]
I'm going to publish this one - I feel it is useful even if we can't provide a placeholder logo image.
