### ISSUE TITLE
Simple centered footer

### ISSUE THREAD

**Issue by alaczek** [Automattic/blockpatterns#254]
This pattern contains the WordPress.com credit only.
<img width="1066" alt="image" src="https://user-images.githubusercontent.com/4550351/184562260-53e5606e-3fb3-4447-8976-97e1bfbd35a3.png">

```
<!-- wp:group {"align":"full"} -->
<div class="wp-block-group alignfull"><!-- wp:group {"align":"full","style":{"spacing":{"padding":{"top":"4em","bottom":"2em"}}},"layout":{"inherit":false}} -->
<div class="wp-block-group alignfull" style="padding-top:4em;padding-bottom:2em"><!-- wp:paragraph {"align":"center"} -->
<p class="has-text-align-center">Proudly Powered by <a href="https://wordpress.org">WordPress</a></p>
<!-- /wp:paragraph --></div>
<!-- /wp:group --></div>
<!-- /wp:group -->
```

Preview: https://dotcompatterns.wordpress.com/?p=5873&preview=true

**Comment by alaczek** [comment]
@iamtakashi and @onuro what do you think about this? Is it worth having a pattern like this? Will anyone want to insert just the WP credit? My thinking is we should include WP credit in every pattern we make, but the pattern needs to be more attractive/functional. AFAIK WP credit is included in all themes by default.
(for context this pattern was sourced [from this site](https://headerandfooterpatterns.wordpress.com/))

**Comment by onuro** [comment]
I'm not fully sure. Yet there may be people would want to place this to their site, even if not all. I wonder if we should at least also enrich this by maybe adding the WordPress logo as well?

**Comment by alaczek** [comment]
We might do another pattern that's just a logo, but I think I'll publish this one as is.

**Comment by alaczek** [comment]
Published!
