### ISSUE TITLE
Three columns: text and two images

### ISSUE THREAD

**Issue by alaczek** [Automattic/blockpatterns#28]
I lifted this one from Maywood because it creates some visual interest with the misaligned images (and I personally really like it).

![image](https://user-images.githubusercontent.com/4550351/77137761-4e1e5880-6ac3-11ea-8c67-b0a660a8b4df.png)

```
<!-- wp:columns {"align":"wide"} -->
<div class="wp-block-columns alignwide"><!-- wp:column -->
<div class="wp-block-column"><!-- wp:heading {"level":1} -->
<h1>Enjoy Our Food Experience</h1>
<!-- /wp:heading -->

<!-- wp:paragraph -->
<p>We don't just make food. We make people's experience. Maywood was built on the belief that food should be special, and we carry that belief into everything we do.</p>
<!-- /wp:paragraph -->

<!-- wp:button {"className":"is-style-squared"} -->
<div class="wp-block-button is-style-squared"><a class="wp-block-button__link" href="/menu">View our menu</a></div>
<!-- /wp:button --></div>
<!-- /wp:column -->

<!-- wp:column -->
<div class="wp-block-column"> </div>
<!-- /wp:column --></div>
<!-- /wp:columns -->
```

**Comment by iamtakashi** [comment]
I like this pattern visually, but I think we should make the content a little less verticalized so it's not screaming for a restaurant. And rebuild it with Layout Grid block that is more versatile.

I think you pulled the markup from different section :)

**Comment by ianstewart** [comment]
I think we could use the Pattern Ipsum content here too.

**Comment by alaczek** [comment]
> And rebuild it with Layout Grid block that is more versatile.

I find creating a three-column layout with Layout Grid block problematic when I don't want the section to be full width. With Layout Grid block I can't have two empty columns at the ends, because then I can't distribute the rest equally into three columns (does that make sense?). For this block, I like the wide width option best, but it's not available for the Layout Grid block at all - maybe that's a bug?

Anyway, here's the updated design:

![image](https://user-images.githubusercontent.com/4550351/77493455-509ffa00-6e97-11ea-973c-cf1b27fa73ab.png)


```
<!-- wp:columns {"align":"wide"} -->
<div class="wp-block-columns alignwide"><!-- wp:column -->
<div class="wp-block-column"><!-- wp:paragraph {"fontSize":"small","className":"margin-bottom-half"} -->
<p class="has-small-font-size margin-bottom-half"><span class="uppercase">Your story</span></p>
<!-- /wp:paragraph -->

<!-- wp:heading {"align":"left","className":"margin-top-half"} -->
<h2 class="has-text-align-left margin-top-half">Welcome</h2>
<!-- /wp:heading -->

<!-- wp:paragraph {"align":"left","fontSize":"small"} -->
<p class="has-text-align-left has-small-font-size">At WordPress.com, anyone can start a business, publish a magazine, create a portfolio, make a living, tell a story, start a blog — regardless of income, gender, politics, language, or where “home” is.</p>
<!-- /wp:paragraph -->

<!-- wp:paragraph {"fontSize":"small"} -->
<p class="has-small-font-size">Publish your own words. Be your own boss. Promote your own art. Create your own community. Your ideas are the starting point, your dreams are the destination, and we’re the engine that helps you turn possibility into probability. </p>
<!-- /wp:paragraph --></div>
<!-- /wp:column -->

<!-- wp:column -->
<div class="wp-block-column"><!-- wp:spacer {"height":64} -->
<div style="height:64px" aria-hidden="true" class="wp-block-spacer"></div>
<!-- /wp:spacer -->

<!-- wp:image {"id":288,"sizeSlug":"large"} -->
<figure class="wp-block-image size-large"><img src="https://gutenbaordinghp.files.wordpress.com/2020/03/copper-and-wild-1lbmrktx8gq-unsplash-2.jpg?w=768" class="wp-image-288"/></figure>
<!-- /wp:image --></div>
<!-- /wp:column -->

<!-- wp:column -->
<div class="wp-block-column"><!-- wp:image {"id":289,"sizeSlug":"large"} -->
<figure class="wp-block-image size-large"><img src="https://gutenbaordinghp.files.wordpress.com/2020/03/copper-and-wild-kgrtbslpb3o-unsplash-2.jpg?w=768" class="wp-image-289"/></figure>
<!-- /wp:image -->

<!-- wp:spacer {"height":64} -->
<div style="height:64px" aria-hidden="true" class="wp-block-spacer"></div>
<!-- /wp:spacer --></div>
<!-- /wp:column --></div>
<!-- /wp:columns -->
```

**Comment by iamtakashi** [comment]
> I find creating a three-column layout with Layout Grid block problematic when I don't want the section to be full width. 

Ah, good point. I understand the issue. And, I agree this looks best with `wide` align. Sorry, we'd need to use the core column for now.

The images and the text much better.

I wonder if it looks better if we get rid of the vertical margin between "Your Story" and "Welcome" by changing the custom css classes to `margin-bottom-none` and `margin-top-none`.

**Comment by alaczek** [comment]
> I wonder if it looks better if we get rid of the vertical margin between "Your Story" and "Welcome" by changing the custom css classes to margin-bottom-none and margin-top-none.

I always forget about those additional classes. In this case I think it's a bit too tight - what do you think?

![image](https://user-images.githubusercontent.com/4550351/77608902-98478400-6f72-11ea-8cf3-1704dcd68ec7.png)

**Comment by iamtakashi** [comment]
It is tight, but the small text is uppercased, so I don't mind it.

As we discussed, let's change the text to stay away from the aspirational tone. The images look nice, but I wonder what content would work well with them... someone's favourite stationaries? Not sure :)

I'd try to use images of one subject but taken different parts or angles, and talk about the subject in the text.

**Comment by alaczek** [comment]
Not sure this one still makes sense, since we already have this one: https://dotcompatterns.wordpress.com/2020/07/16/call-to-action-7/

**Comment by iamtakashi** [comment]
Agreed. They are very similar to the existing pattern.
