### ISSUE TITLE
List of posts

### ISSUE THREAD

**Issue by iamtakashi** [Automattic/blockpatterns#305]
**Category:** Blog, Wireframe

**Tag:** Pattern, Layout

**Screenshot:**
![dotcompatterns wordpress com__p=8437 preview=true query-4-page=2 (1)](https://user-images.githubusercontent.com/908665/200743361-f2c698b5-5161-4df0-be1b-f2b9ac4f4426.png)

**Markup:**
```
<!-- wp:group {"align":"full","layout":{"type":"constrained"}} -->
<div class="wp-block-group alignfull"><!-- wp:query {"queryId":4,"query":{"perPage":"10","pages":0,"offset":0,"postType":"post","order":"desc","orderBy":"date","author":"","search":"","exclude":[],"sticky":"","inherit":false}} -->
<div class="wp-block-query"><!-- wp:post-template -->
<!-- wp:group {"style":{"spacing":{"blockGap":"1.5rem","padding":{"bottom":"3rem"}}},"layout":{"type":"constrained"}} -->
<div class="wp-block-group" style="padding-bottom:3rem"><!-- wp:group {"style":{"spacing":{"blockGap":"var:preset|spacing|20"}},"layout":{"type":"constrained"}} -->
<div class="wp-block-group"><!-- wp:post-date /-->

<!-- wp:post-title {"isLink":true,"style":{"elements":{"link":{"color":{"text":"var:preset|color|foreground"}}},"typography":{"fontStyle":"normal","fontWeight":"700"}}} /--></div>
<!-- /wp:group -->

<!-- wp:post-featured-image {"isLink":true} /-->

<!-- wp:post-excerpt {"moreText":"Read more"} /--></div>
<!-- /wp:group -->
<!-- /wp:post-template -->

<!-- wp:query-pagination {"paginationArrow":"chevron","layout":{"type":"flex","justifyContent":"space-between"}} -->
<!-- wp:query-pagination-previous /-->

<!-- wp:query-pagination-numbers /-->

<!-- wp:query-pagination-next /-->
<!-- /wp:query-pagination --></div>
<!-- /wp:query --></div>
<!-- /wp:group -->
```

**Preview:** https://dotcompatterns.wordpress.com/?p=8437&preview=true

cc @alaczek @onuro

**Comment by onuro** [comment]
Looking good but I wonder if each post container could use a bit more bottom spacing since with excerpts on, the next post seems to be too close to the previous one.

<img width="1785" alt="image" src="https://user-images.githubusercontent.com/645713/201984156-445474d5-a74b-4124-af24-8b50f0823ef5.png">

**Comment by iamtakashi** [comment]
> the next post seems to be too close to the previous one.

@onuro, what theme was that? 

Contrary to #303, the generous unit in TT3 works better for this 😂.

![iamtakashi jurassic tube__page_id=544 (3)](https://user-images.githubusercontent.com/908665/202145941-0a3aad3f-6883-4a82-882c-28a9e5583e4c.png)

Anyway, I updated to use an absolute value so that the spacing appears the same in all themes. I don't think I'm going to use the range control anymore 😀 Does it look good with the theme now?

**Comment by onuro** [comment]
Yes, much better!

> @onuro, what theme was that?

It was TT3 and one more theme but I forgot I think it was Skatepark.

**Comment by iamtakashi** [comment]
Thanks! Published.
