### ISSUE TITLE
Hero (heading, subtitle, and two buttons)

### ISSUE THREAD

**Issue by alaczek** [Automattic/blockpatterns#67]
Last one from Leven, I promise 🙂I noticed we don't have yet this super popular "hero" pattern with heading and two buttons.

![image](https://user-images.githubusercontent.com/4550351/82167789-2d765180-9900-11ea-8694-eff132422211.png)

```
<!-- wp:group {"align":"full"} -->
<div class="wp-block-group alignfull"><div class="wp-block-group__inner-container"><!-- wp:heading {"level":1,"placeholder":"Add heading...","textColor":"foreground-dark"} -->
<h1 class="has-foreground-dark-color has-text-color">A Curated Collection of Refurbished Vintage Cameras &amp; Accessories.</h1>
<!-- /wp:heading -->

<!-- wp:paragraph -->
<p>Lenses, filters, lighting and more. All in working condition at unbeatable prices.</p>
<!-- /wp:paragraph -->

<!-- wp:buttons -->
<div class="wp-block-buttons"><!-- wp:button {"style":{"color":{"background":"#ff302c"}}} -->
<div class="wp-block-button"><a class="wp-block-button__link has-background" style="background-color:#ff302c">Learn more</a></div>
<!-- /wp:button -->

<!-- wp:button {"style":{"color":{"text":"#ff302c"}},"className":"is-style-outline"} -->
<div class="wp-block-button is-style-outline"><a class="wp-block-button__link has-text-color" style="color:#ff302c">Pre-order</a></div>
<!-- /wp:button --></div>
<!-- /wp:buttons -->

<!-- wp:spacer {"height":32} -->
<div style="height:32px" aria-hidden="true" class="wp-block-spacer"></div>
<!-- /wp:spacer --></div></div>
<!-- /wp:group -->

<!-- wp:paragraph -->
<p></p>
<!-- /wp:paragraph -->
```

**Comment by ianstewart** [comment]
I think I would just drop the period in the heading on this one.

**Comment by iamtakashi** [comment]
And an extra empty paragraph is there :)

**Comment by iamtakashi** [comment]
Do we need that group block? Can we just use default text colour for the heading instead of the theme defined colour?

**Comment by alaczek** [comment]
> And an extra empty paragraph is there :)

Those empty paragraphs will be the death of me :|

The group makes it easy to add background color, but I'm not sure people would realize that anyway, so I'll get rid of it. What are your thoughts on including spacers before/after?

```
<!-- wp:heading {"level":1,"placeholder":"Add heading..."} -->
<h1>A Curated Collection of Refurbished Vintage Cameras &amp; Accessories</h1>
<!-- /wp:heading -->

<!-- wp:paragraph -->
<p>Lenses, filters, lighting and more. All in working condition at unbeatable prices.</p>
<!-- /wp:paragraph -->

<!-- wp:buttons -->
<div class="wp-block-buttons"><!-- wp:button {"style":{"color":{"background":"#ff302c"}}} -->
<div class="wp-block-button"><a class="wp-block-button__link has-background" style="background-color:#ff302c">Learn more</a></div>
<!-- /wp:button -->

<!-- wp:button {"style":{"color":{"text":"#ff302c"}},"className":"is-style-outline"} -->
<div class="wp-block-button is-style-outline"><a class="wp-block-button__link has-text-color" style="color:#ff302c">Pre-order</a></div>
<!-- /wp:button --></div>
<!-- /wp:buttons -->

<!-- wp:spacer {"height":32} -->
<div style="height:32px" aria-hidden="true" class="wp-block-spacer"></div>
<!-- /wp:spacer -->
```

**Comment by iamtakashi** [comment]
> Those empty paragraphs will be the death of me :|

I know, it's so easy to get it and annoying, but it will mess up vertical margins so it's good to have a quick check of the markup when you produce a pattern.

> The group makes it easy to add background color, but I'm not sure people would realize that anyway, so I'll get rid of it.

👍 

> What are your thoughts on including spacers before/after?

I think that helps in this case. Maybe, 60px or something a little more than 32px?

**Comment by alaczek** [comment]
I've been thinking about this one a bit more - would it make sense to wrap this whole thing in a cover block? This way everything would be vertically aligned middle, I wouldn't need extra spacers and changing background color would be easy. I actually like it better with a light-grey background by default. The only downside is I'd need to specify the text color.

![image](https://user-images.githubusercontent.com/4550351/82508740-563d5780-9b49-11ea-94f0-d81e615e8622.png)


```
<!-- wp:cover {"customOverlayColor":"#f7f7f7","align":"full"} -->
<div class="wp-block-cover alignfull has-background-dim" style="background-color:#f7f7f7"><div class="wp-block-cover__inner-container"><!-- wp:heading {"level":1,"placeholder":"Add heading...","style":{"typography":{"lineHeight":"1.4"},"color":{"text":"#222222"}}} -->
<h1 class="has-text-color" style="line-height:1.4;color:#222222">A Curated Collection of Refurbished Vintage Cameras &amp; Accessories</h1>
<!-- /wp:heading -->

<!-- wp:paragraph {"style":{"color":{"text":"#222222"}}} -->
<p class="has-text-color" style="color:#222222">Lenses, filters, lighting and more. All in working condition at unbeatable prices.</p>
<!-- /wp:paragraph -->

<!-- wp:buttons -->
<div class="wp-block-buttons"><!-- wp:button {"style":{"color":{"background":"#ff302c","text":"#ffffff"}}} -->
<div class="wp-block-button"><a class="wp-block-button__link has-text-color has-background" style="background-color:#ff302c;color:#ffffff">Learn more</a></div>
<!-- /wp:button -->

<!-- wp:button {"style":{"color":{"text":"#ff302c"}},"className":"is-style-outline"} -->
<div class="wp-block-button is-style-outline"><a class="wp-block-button__link has-text-color" style="color:#ff302c">Pre-order</a></div>
<!-- /wp:button --></div>
<!-- /wp:buttons --></div></div>
<!-- /wp:cover -->
```

**Comment by iamtakashi** [comment]
I like it better within a Cover or Group block with a background too. With the Cover block, the customer can change the height easily without using some spacers. The only thing that has been stopping me to use more is the lack of text colour setting. It'd be a good question or an issue to raise in the Gutenberg repo.

I usually use a Layout Grid inside a cover or a group, but both methods have pros and cons.

It looks good to me!

**Comment by ianstewart** [comment]
Plus one for being inside of the cover. It feels more "solid" as a pattern.

**Comment by pablohoneyhoney** [comment]
The line height on heading can be tighter. And have an even spacing between elements.

**Comment by alaczek** [comment]
I've decreased the heading line-height to 1.2. I also previewed the pattern in a few different themes, and I'm thinking the screenshot above (from Leven) is an outlier - most have good size contrast, which I'd rather not touch to stay consistent with overall theme typography.

Here are some screenshots from a few different themes (I know some have widows in them, but right now there's nothing we can do about it):

Alves
![image](https://user-images.githubusercontent.com/4550351/95409598-b6545f00-096d-11eb-8b9c-1d50ccadc156.png)

Maywood
![image](https://user-images.githubusercontent.com/4550351/95409694-ee5ba200-096d-11eb-9b0c-e85dc9e47d58.png)

Balasana
![image](https://user-images.githubusercontent.com/4550351/95409895-675af980-096e-11eb-89ea-b57574551d79.png)
