### ISSUE TITLE
Image and Quote

### ISSUE THREAD

**Issue by iamtakashi** [Automattic/blockpatterns#96]
![Pattern 106](https://user-images.githubusercontent.com/908665/87695616-999df600-c787-11ea-9a56-ec2d220a7294.jpg)

```
<!-- wp:group {"align":"full","textColor":"foreground-dark","style":{"color":{"background":"#d1814f"}}} -->
<div class="wp-block-group alignfull has-foreground-dark-color has-text-color has-background" style="background-color:#d1814f"><div class="wp-block-group__inner-container"><!-- wp:spacer {"height":64} -->
<div style="height:64px" aria-hidden="true" class="wp-block-spacer"></div>
<!-- /wp:spacer -->

<!-- wp:columns {"verticalAlignment":"center","align":"wide"} -->
<div class="wp-block-columns alignwide are-vertically-aligned-center"><!-- wp:column {"verticalAlignment":"center","width":32} -->
<div class="wp-block-column is-vertically-aligned-center" style="flex-basis:32%"><!-- wp:image {"id":1709,"sizeSlug":"large"} -->
<figure class="wp-block-image size-large"><img src="https://dotcompatterns.files.wordpress.com/2020/07/prince-akachi-lwkfhegplee-unsplash.jpg" alt="" class="wp-image-1709"/></figure>
<!-- /wp:image --></div>
<!-- /wp:column -->

<!-- wp:column {"verticalAlignment":"center","width":68} -->
<div class="wp-block-column is-vertically-aligned-center" style="flex-basis:68%"><!-- wp:paragraph {"style":{"typography":{"fontSize":29,"lineHeight":"1.38"}}} -->
<p style="line-height:1.38;font-size:29px">“I strongly believe that the power of food has a fundamental place in people’s homes that binds us to the best things of life.”</p>
<!-- /wp:paragraph -->

<!-- wp:paragraph {"style":{"typography":{"fontSize":20,"lineHeight":"1.65"}}} -->
<p style="line-height:1.65;font-size:20px">— Lakin Smith</p>
<!-- /wp:paragraph --></div>
<!-- /wp:column --></div>
<!-- /wp:columns -->

<!-- wp:spacer {"height":64} -->
<div style="height:64px" aria-hidden="true" class="wp-block-spacer"></div>
<!-- /wp:spacer --></div></div>
<!-- /wp:group -->
```

**Comment by ianstewart** [comment]
I really like the color scheme with this one. Works well with the photo — and brings some variety with what's shipped.

Did you try out different gutter widths between the two columns?

**Comment by iamtakashi** [comment]
> Did you try out different gutter widths between the two columns?

I wanted to give a bit more, but there is no setting in the block at the moment. There is an issue for it, but it doesn't seem to get too much attention. https://github.com/WordPress/gutenberg/issues/10730

**Comment by ianstewart** [comment]
Can you add to your todo list a before/after of the block and add the images to that core issue? Just for a "here's an example of the kind of control I'd like to have when working on a site design with Gutenberg" kind of comment. The visual example will be easier to understand than the code example that opened the issue. :)

**Comment by iamtakashi** [comment]
Good idea. Will do!

**Comment by ianstewart** [comment]
Cool. LGTM for now on the above though. :shipit:

**Comment by iamtakashi** [comment]
I decided to open a new one as the one that I found started with a wrong approach :) 

Columns Block: Provide Gutter Size Control: https://github.com/WordPress/gutenberg/issues/24058

**Comment by pablohoneyhoney** [comment]
- A bit more space between image and text?
- Perhaps the quote lightly bigger.

**Comment by iamtakashi** [comment]
> A bit more space between image and text?

Yes, we'd like to be able to change the gutter size in the Column block, and there is a long-standing issue in Gutenberg repo, but not getting too much attention at the moment. https://github.com/WordPress/gutenberg/issues/10730

> Perhaps the quote lightly bigger.

I increased a bit the size of the quote and the line-height.

![Pattern 106](https://user-images.githubusercontent.com/908665/93648060-c11c7380-fa01-11ea-8ae7-5af91d342eb9.jpg)

**Comment by alaczek** [comment]
Closing the loop on that one, as it's already launched.
